/*

Filename: layout_map.c 

Map Include File

 Info:
   Section       :
   Bank          : 0
   Map size      : 20 x 18
   Tile offset   : 0

This file was generated by: Gimp/Console png2gbtiles
*/

#define layout_map_width 20
#define layout_map_height 18
#define layout_map_tiles 360
#define layout_map_bytes 360

extern unsigned char layout_map[];
extern unsigned char layout_map_attr[];

